/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as ApiPublicWompiWebhookRouteImport } from './routes/api/public/wompi-webhook'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWompiWebhookRoute = ApiPublicWompiWebhookRouteImport.update({
  id: '/api/public/wompi-webhook',
  path: '/api/public/wompi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/api/public/wompi-webhook': typeof ApiPublicWompiWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/api/public/wompi-webhook': typeof ApiPublicWompiWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/api/public/wompi-webhook': typeof ApiPublicWompiWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/admin/payments' | '/api/public/wompi-webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/admin/payments' | '/api/public/wompi-webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/payments'
    | '/api/public/wompi-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  ApiPublicWompiWebhookRoute: typeof ApiPublicWompiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wompi-webhook': {
      id: '/api/public/wompi-webhook'
      path: '/api/public/wompi-webhook'
      fullPath: '/api/public/wompi-webhook'
      preLoaderRoute: typeof ApiPublicWompiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  ApiPublicWompiWebhookRoute: ApiPublicWompiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
